# manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  namespace: dev
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1  # Première version
        ports:
        - containerPort: 8888
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
